version: '3'
services:
  nginx:
    ports:
      - '3000:80'

  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=root
      - MONGO_PASS=pass
      - SESSION_SECRET=secret
    command: npm run dev

  mongo:
    image: mongo
    volumes:
      - mongo-db-dev:/data/db

volumes:
  mongo-db-dev:
